name: deploy-container-old

on:
  push:
    branches:
      - master
    paths:
      - "packages/container/**"

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-east-1


 #     - name: Remove from S3
 #       uses: vitorsgomes/s3-rm-action@master
 #       with:
 #         args: --recursive
 #       env:
 #         AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
 #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 #         AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
 #         PATH_TO_DELETE: 'container/latest/'


 #     - name: Copy files to the s3 website content bucket
 #       uses: jakejarvis/s3-sync-action@master
 #       with:
 #         args: --acl public-read --follow-symlinks --delete
 #       env:
 #         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
 #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 #         AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
 #         SOURCE_DIR: './dist'      # optional: defaults to entire repository
 #         DEST_DIR: '/container/latest'      # optional: defaults to entire repository
